package net.plazmix.skywars.state;

import lombok.NonNull;
import net.md_5.bungee.api.ChatMessageType;
import net.plazmix.core.PlazmixCoreApi;
import net.plazmix.game.GameCache;
import net.plazmix.game.GamePlugin;
import net.plazmix.game.state.type.StandardWaitingState;
import net.plazmix.game.user.GameUser;
import net.plazmix.game.utility.GameSchedulers;
import net.plazmix.game.utility.hotbar.GameHotbar;
import net.plazmix.game.utility.hotbar.GameHotbarBuilder;
import net.plazmix.skywars.scoreboard.WaitingScoreboard;
import net.plazmix.skywars.util.Actionbar;
import net.plazmix.skywars.util.GameConstants;
import net.plazmix.utility.ItemUtil;
import net.plazmix.utility.PlayerUtil;
import net.plazmix.utility.leveling.LevelingUtil;
import net.plazmix.utility.location.LocationUtil;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;
import org.bukkit.scheduler.BukkitRunnable;

public final class WaitingState extends StandardWaitingState {

    private final GameHotbar gameHotbar = GameHotbarBuilder.newBuilder()
            .setMoveItems(false)
            .addItem(5, ItemUtil.newBuilder(Material.SKULL_ITEM)
                            .setDurability(3)
                            .setTextureValue("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2UzZGViNTdlYWEyZjRkNDAzYWQ1NzI4M2NlOGI0MTgwNWVlNWI2ZGU5MTJlZTJiNGVhNzM2YTlkMWY0NjVhNyJ9fX0=")
                            .setName("§aМагазин §7(ПКМ)")
                            .build(),

                    player -> plugin.getService().createCategoriesAutoGeneratedMenu(5, "Магазин").openInventory(player))

            .addItem(9, ItemUtil.newBuilder(Material.SKULL_ITEM)
                            .setDurability(3)
                            .setTextureValue("eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjhkNmFkNjkyN2NkYWE5ZDgxNzkzMzdjYWRmOTY0NDYwNjcyMTE3YjMyNmU2MGY1YjFkMTlhNGI1NGYyYTMyMyJ9fX0=")
                            .setName("§aПокинуть арену §7(ПКМ)")
                            .build(),

                    PlazmixCoreApi::redirectToLobby)
            .build();

    private BukkitRunnable actionbarAnnounceTask;

    public WaitingState(@NonNull GamePlugin plugin) {
        super(plugin, "Ожидание игроков");
    }

    @Override
    protected void onStart() {
        if (this.actionbarAnnounceTask == null) {
            this.actionbarAnnounceTask = new BukkitRunnable() {

                @Override
                public void run() {
                    for (Player player : Bukkit.getOnlinePlayers()) {
                        GameCache gameCache = GameUser.from(player).getCache();

                        int skywarsLevel = LevelingUtil.getLevel(gameCache.getInt(GameConstants.DATABASE_PLAYER_EXP));
                        int damnGamePercent = gameCache.getInt(GameConstants.DATABASE_PLAYER_DAMN_PERCENT);

                        Actionbar.sendMessage(player, String.format("§7Skywars уровень: §b%d LVL §8§l§k| §7Шанс проклятой игры: §c%d%%", skywarsLevel, damnGamePercent));
                    }
                }
            };

            this.actionbarAnnounceTask.runTaskTimer(super.getPlugin(), 10, 10);
        }

        super.onStart();
    }

    @Override
    protected void onShutdown() {
        if (this.actionbarAnnounceTask != null) {
            this.actionbarAnnounceTask.cancel();
        }

        super.getPlugin().broadcastMessage(ChatMessageType.ACTION_BAR, "");
        super.onShutdown();
    }

    @Override
    protected Location getTeleportLocation() {
        return LocationUtil.stringToLocation(plugin.getConfig().getString("wait-lobby-spawn"));
    }

    @Override
    protected void handleEvent(@NonNull PlayerJoinEvent event) {
        int online = Bukkit.getOnlinePlayers().size();
        int maxOnline = getPlugin().getService().getMaxPlayers();

        // В шедулере, потому что баккит так хочет :(
        GameSchedulers.runLater(10, () -> {

            new WaitingScoreboard(getTimerStatus(), event.getPlayer());
            gameHotbar.setHotbarTo(event.getPlayer());
        });

        event.setJoinMessage(GameConstants.PREFIX + PlayerUtil.getDisplayName(event.getPlayer()) + " §fподключился к игре §7(" + online + "/" + maxOnline + ")");

        // Если сервер полный, то запускаем таймер
        if (online >= maxOnline && !timerStatus.isLived()) {
            timerStatus.runTask();
        }
    }

    @Override
    protected void handleEvent(@NonNull PlayerQuitEvent event) {
        int online = Bukkit.getOnlinePlayers().size() - 1;
        int maxOnline = getPlugin().getService().getMaxPlayers();

        event.setQuitMessage(GameConstants.PREFIX + PlayerUtil.getDisplayName(event.getPlayer()) + " §fпокинул игру §7(" + online + "/" + maxOnline + ")");

        // Если кто-то вышел, то надо вырубать таймер
        if (online < maxOnline && timerStatus.isLived()) {
            timerStatus.cancelTask();
        }
    }

    @Override
    protected void handleTimerUpdate(@NonNull TimerStatus timerStatus) {
    }
}
